variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - check
  - deploy

before_script:
    - security unlock-keychain -p ${DEFAULT_KEYCHAIN_PASSWORD} ~/Library/Keychains/login.keychain-db
    - dmenv install
    - dmenv run -- python run-ci.py --isolate-conan-user-home update-conan-config

check/deployed-native:
  stage: check
  when: manual
  except:
    - tags
  script:
    - dmenv run -- python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=deployed
  tags:
    - macos

check/native-from-sources:
  stage: check
  when: manual
  except:
    - tags
  script:
    - dmenv run -- python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=same-as-branch
  tags:
    - macos

nightly:
  stage: check
  only:
    - schedules
  script:
    - dmenv run -- python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=same-as-branch --notifier=mail
  tags:
    - macos

deploy:
  stage: deploy
  when: manual
  only:
    - tags
  script:
    - dmenv run -- python run-ci.py deploy --git-tag ${CI_COMMIT_TAG}
  tags:
    - macos

mirror:
  tags:
    - macos
  stage: deploy
  only:
    # mirror public tags, releases branches
    # and master
    - /\Av[0-9.]+\z/
    - master
    - /\Arelease/.*\z/
  except:
    - schedules
  script:
    - dmenv run python run-ci.py mirror
