[version]
current = "dev"

regex = '''
  (dev)
  |
  (
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  (
    -
    (?P<channel>alpha|beta|r)
    (?P<release>\d+)
  )?
  )
'''

[git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"

[[file]]
src = "Tanker/Tanker.in.podspec"
search = 's.version'

[[file]]
src = "Tanker/Tanker/Classes/TKRTanker.m"
search = '#define TANKER_IOS_VERSION @"{current_version}"'
