[version]
current = "9999.0.0"

regex = '''
  (dev)
  |
  (
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  (
    -
    (?P<channel>alpha|beta|r)
    (?P<release>\d+)
  )?
  )
'''

[git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"

[[file]]
src = "Tanker/Tanker.podspec"
search = 's.version'

[[file]]
src = "Tanker/Sources/TKRTanker.swift"
search = 'static let TANKER_IOS_VERSION = "{current_version}";'
