source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/TankerHQ/PodSpecs.git'

use_frameworks!
platform :ios, '9.0'

target 'Tanker_Example' do
  pod 'Tanker', :path => '../Tanker.podspec', :testspecs => ['Tests']

  target 'Tanker_Tests' do
    inherit! :search_paths


  end
end
