use_frameworks!
platform :ios, '12.0'

target 'Tanker_Example' do
  pod 'Tanker', :path => '../Tanker.podspec', :testspecs => ['Tests']

  target 'Tanker_Tests' do
    inherit! :search_paths


  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
